kind: Deployment
apiVersion: apps/v1
metadata:
  name: pdb-tester
  labels:
    app: pdb-tester
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pdb-tester
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 40%
  template:
    metadata:
      labels:
        app: pdb-tester
    spec:
      containers:
      - image: nginx
        name: pdb-tester